#!/bin/bash
# Helper script to check and copy QSys generated files

QSYS_FILE="$1"
QSYS_DIR="$2"
GENERATED_DIR="$3"
QSYS_BASE="$4"
QSYS_STAMP="$5"
QSYS_SOPCINFO="$6"
QSYS_GENERATE_CMD="${7:-qsys-generate}"

# Check if files already exist in expected location
if [ -f "$QSYS_SOPCINFO" ] && [ -f "$GENERATED_DIR/$QSYS_BASE/synthesis/$QSYS_BASE.qip" ]; then
	echo "QSys files already exist in $GENERATED_DIR/$QSYS_BASE/"
	echo "Skipping generation (using existing files)"
	mkdir -p "$(dirname "$QSYS_STAMP")"
	touch "$QSYS_STAMP"
	exit 0
fi

# Check if files exist in GUI location
if [ -d "$QSYS_DIR/$QSYS_BASE/synthesis" ] && [ -f "$QSYS_DIR/$QSYS_BASE/synthesis/$QSYS_BASE.qip" ]; then
	echo "Found QSys files generated by Platform Designer GUI in $QSYS_DIR/$QSYS_BASE/"
	echo "Copying to $GENERATED_DIR/$QSYS_BASE/..."
	mkdir -p "$GENERATED_DIR/$QSYS_BASE"
	cp -r "$QSYS_DIR/$QSYS_BASE/synthesis" "$GENERATED_DIR/$QSYS_BASE/"
	if [ -f "$QSYS_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo" ]; then
		cp "$QSYS_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo" "$QSYS_SOPCINFO"
	elif [ -f "$GENERATED_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo" ]; then
		cp "$GENERATED_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo" "$QSYS_SOPCINFO"
	fi
	echo "Files copied successfully"
	echo "QSys generation complete (using GUI-generated files)"
	mkdir -p "$(dirname "$QSYS_STAMP")"
	touch "$QSYS_STAMP"
	exit 0
fi

# Files don't exist, need to generate
echo "Generating QSys system: $QSYS_FILE"
echo "Output directory: $GENERATED_DIR"

if ! command -v "$QSYS_GENERATE_CMD" >/dev/null 2>&1 && [ ! -f "$QSYS_GENERATE_CMD" ]; then
	echo ""
	echo "ERROR: qsys-generate command not found"
	echo "  Tried: $QSYS_GENERATE_CMD"
	echo "Quartus Prime tools are required for QSys generation."
	echo ""
	echo "Installation:"
	echo "  1. Install Quartus Prime from Intel FPGA Software Center"
	echo "  2. Add Quartus bin directory to PATH:"
	echo "     export PATH=\$PATH:/path/to/intelFPGA/20.1/quartus/bin"
	echo ""
	echo "Or use Platform Designer GUI:"
	echo "  make qsys_edit  # Opens Platform Designer GUI"
	echo "  Then: File -> Generate -> Generate HDL"
	echo ""
	echo "Note: If Quartus is installed on Windows, the Makefile should"
	echo "  auto-detect it. If not, manually add to PATH:"
	echo "    export PATH=\$PATH:/mnt/c/intelFPGA_lite/20.1/quartus/bin64"
	echo ""
	exit 1
fi

echo "This may take several minutes..."
# Note: SET_QSYS_GENERATE_ENV is handled by Makefile if needed (for Cygwin)
"$QSYS_GENERATE_CMD" "$QSYS_FILE" --synthesis=VERILOG --output-directory="$GENERATED_DIR/$QSYS_BASE" || {
	echo ""
	echo "WARNING: QSys generation completed with errors (this may be non-critical)."
	echo "HPS SDRAM generation errors are common if SoC EDS is not installed."
	echo "Checking if critical files were generated..."
	if [ -f "$QSYS_SOPCINFO" ] && [ -f "$GENERATED_DIR/$QSYS_BASE/synthesis/$QSYS_BASE.qip" ]; then
		echo "Critical files found - Quartus compilation may still work."
		echo "Try compiling in Quartus. If it fails, install SoC EDS."
	else
		echo "ERROR: Critical files missing. Please install SoC EDS and retry."
		exit 1
	fi
}

if [ -f "$GENERATED_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo" ]; then
	cp "$GENERATED_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo" "$QSYS_SOPCINFO"
fi

mkdir -p "$(dirname "$QSYS_STAMP")"
touch "$QSYS_STAMP"
