#!/bin/bash
# Helper script to check and copy QSys generated files.
#
# This script is called by `FPGA/Makefile` to:
# - Reuse existing generated artifacts when available
# - Generate QSys HDL/sopcinfo when missing
# - Copy generated outputs into the GUI-visible directory for Platform Designer compatibility

set -euo pipefail

QSYS_FILE="$1"
QSYS_DIR="$2"
GENERATED_DIR="$3"
QSYS_BASE="$4"
QSYS_STAMP="$5"
QSYS_SOPCINFO="$6"
QSYS_GENERATE_CMD="${7:-qsys-generate}"

# qsys-generate creates a synthesis/ subdirectory automatically, so output to parent
generatedOutputDir="$GENERATED_DIR/$QSYS_BASE"
generatedSynthesisDir="$generatedOutputDir/synthesis"
generatedSopcinfo1="$GENERATED_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo"
generatedSopcinfo2="$generatedSynthesisDir/$QSYS_BASE.sopcinfo"
guiDir="$QSYS_DIR/$QSYS_BASE"
guiSynthesisDir="$guiDir/synthesis"
guiSopcinfo="$guiDir/$QSYS_BASE.sopcinfo"

ensure_stamp() {
	mkdir -p "$(dirname "$QSYS_STAMP")"
	touch "$QSYS_STAMP"
}

copy_sopcinfo_if_present() {
	if [ -f "$generatedSopcinfo1" ]; then
		cp "$generatedSopcinfo1" "$QSYS_SOPCINFO"
	elif [ -f "$generatedSopcinfo2" ]; then
		cp "$generatedSopcinfo2" "$QSYS_SOPCINFO"
	fi
}

# Case 1: Already have the “expected” Makefile outputs.
if [ -f "$QSYS_SOPCINFO" ] && [ -f "$generatedSynthesisDir/$QSYS_BASE.qip" ]; then
	echo "QSys files already exist in $GENERATED_DIR/$QSYS_BASE/"
	echo "Copying to GUI location ($guiDir/) for GUI compatibility..."
	mkdir -p "$guiDir"
	if [ -d "$generatedSynthesisDir" ]; then
		cp -r "$generatedSynthesisDir" "$guiDir/" 2>/dev/null || true
	fi
	if [ -f "$QSYS_SOPCINFO" ] && [ ! -f "$guiSopcinfo" ]; then
		cp "$QSYS_SOPCINFO" "$guiSopcinfo" 2>/dev/null || true
	fi
	echo "Skipping generation (using existing files)"
	ensure_stamp
	exit 0
fi

# Case 2: Have GUI-generated outputs; copy them to the Makefile-generated directory.
if [ -d "$guiSynthesisDir" ] && [ -f "$guiSynthesisDir/$QSYS_BASE.qip" ]; then
	echo "Found QSys files generated by Platform Designer GUI in $guiDir/"
	echo "Copying to $GENERATED_DIR/$QSYS_BASE/..."
	mkdir -p "$GENERATED_DIR/$QSYS_BASE"
	cp -r "$guiSynthesisDir" "$GENERATED_DIR/$QSYS_BASE/"
	if [ -f "$guiSopcinfo" ]; then
		cp "$guiSopcinfo" "$QSYS_SOPCINFO"
	else
		copy_sopcinfo_if_present
	fi
	echo "Files copied successfully"
	echo "QSys generation complete (using GUI-generated files)"
	ensure_stamp
	exit 0
fi

# Case 3: Need to generate using qsys-generate.
echo "Generating QSys system: $QSYS_FILE"
echo "Output directory: $GENERATED_DIR"

if ! command -v "$QSYS_GENERATE_CMD" >/dev/null 2>&1 && [ ! -f "$QSYS_GENERATE_CMD" ]; then
	echo ""
	echo "ERROR: qsys-generate command not found"
	echo "  Tried: $QSYS_GENERATE_CMD"
	echo "Quartus Prime tools are required for QSys generation."
	echo ""
	echo "Install Quartus Prime and ensure the Quartus bin directory is on PATH."
	exit 1
fi

echo "This may take several minutes..."
mkdir -p "$generatedOutputDir"

# Note: SET_QSYS_GENERATE_ENV is handled by Makefile if needed (for Cygwin)
# qsys-generate will create synthesis/ subdirectory automatically
"$QSYS_GENERATE_CMD" "$QSYS_FILE" --synthesis=VERILOG --output-directory="$generatedOutputDir" || {
	echo ""
	echo "WARNING: QSys generation completed with errors (this may be non-critical)."
	echo "Checking if critical files were generated..."
	if [ -f "$generatedSynthesisDir/$QSYS_BASE.qip" ]; then
		echo "Critical QIP found - Quartus compilation may still work."
	else
		echo "ERROR: Critical files missing. Ensure Quartus Prime is properly installed."
		exit 1
	fi
}

copy_sopcinfo_if_present

# Copy generated files to GUI location for GUI compatibility
if [ -d "$generatedSynthesisDir" ]; then
	echo "Copying generated files to GUI location ($guiDir/) for GUI compatibility..."
	mkdir -p "$guiDir"
	cp -r "$generatedSynthesisDir" "$guiDir/" 2>/dev/null || true
	if [ -f "$QSYS_SOPCINFO" ] && [ ! -f "$guiSopcinfo" ]; then
		cp "$QSYS_SOPCINFO" "$guiSopcinfo" 2>/dev/null || true
	fi
fi

ensure_stamp
